parameters:
    data_nova.server_url: http://datanova.laposte.fr
    data_nova.api.version: '1.0'
    data_nova.client.timeout: 3.0

services:
    data_nova.provider.records:
        class: Laposte\DatanovaBundle\Provider\Records
        arguments:
            - '%data_nova.server_url%'
            - '%data_nova.api.version%'
        calls:
            - ['setLogger', ['@?logger']]
            - ['setTimeout', ['%data_nova.client.timeout%']]

    data_nova.service.records.codes_postaux:
        class: Laposte\DatanovaBundle\Service\Records\CodesPostaux
        arguments:
            - '@data_nova.provider.records'
