parameters:
    data_nova.server_url: http://datanova.laposte.fr
    data_nova.api.version: '1.0'
    data_nova.client.timeout: 3.0
    data_nova.download_dir: 'Resources/dataset/'

services:
    data_nova.provider.curl_client:
        class: Laposte\DatanovaBundle\Provider\CurlClient
        arguments:
            - '%data_nova.server_url%'
            - '%data_nova.api.version%'
        calls:
            - ['setLogger', ['@?logger']]
            - ['setTimeout', ['%data_nova.client.timeout%']]

    data_nova.service.downloader:
        class: Laposte\DatanovaBundle\Service\Downloader
        arguments:
            - '@data_nova.provider.curl_client'
            - '@data_nova.service.finder'

    data_nova.service.finder:
        class: Laposte\DatanovaBundle\Service\Finder
        arguments:
            - '@filesystem' #FIXME
            - '%kernel.root_dir%'
        calls:
            - ['setLogger', ['@?logger']]
            - ['setWorkingDirectory', ['%data_nova.download_dir%']]

    data_nova.command.records.download:
        class: Laposte\DatanovaBundle\Command\DownloadRecordsCommand
        arguments:
            - '@data_nova.service.downloader'
        tags:
            -  { name: console.command }

    data_nova.service.records.codes_postaux:
        class: Laposte\DatanovaBundle\Service\Records\CodesPostaux
        arguments:
            - '@data_nova.provider.curl_client'
