language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:2.3.* --prefer-source --no-update  --no-interaction
    - composer update --prefer-source --dev --no-interaction

script:
    - bin/phpunit --coverage-text

notifications:
  email:
    - florianajir@gmail.com
