language: php
php:
  - '5.5'
  - '7.0'

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source --no-update  --no-interaction
    - composer update --prefer-source --dev --no-interaction

script:
    - bin/phpunit --coverage-text

notifications:
  email:
    - florianajir@gmail.com
