data_nova.api.records.search:
    path:     /records/search/{dataset}/{query}/{sort}/{rows}/{start}
    defaults:
        _controller: LaposteDatanovaBundle:Records:search
        _format: json
        query: null
        sort: ''
        rows: 10
        start: 0

data_nova.api.records.download:
    path:     /records/download/{dataset}.{_format}/{query}
    defaults:
        _controller: LaposteDatanovaBundle:Records:download
        _format: json
        query: ''
    requirements:
        _format: json|csv
